events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream django_backend {
        server web:8000;
    }

    # HTTP'den HTTPS'e yönlendirme
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl;
        server_name localhost;

        # SSL certificates
        ssl_certificate /etc/nginx/ssl/ssl.crt;
        ssl_certificate_key /etc/nginx/ssl/ssl.key;

        # SSL protocols and ciphers
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Static files
        location /static/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
            
            # JS files
            location ~ \.js$ {
                add_header Content-Type "application/javascript" always;
            }

            # Images
            location ~ \.(png|jpg|jpeg|gif)$ {
                try_files $uri =404;
            }
        }

        # Ana sayfa için Django
        location = / {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect http://127.0.0.1:8000/ https://127.0.0.1/;
        }

        # API rotaları için Django
        location ~ ^/(api|django|authapp)/ {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect http://127.0.0.1:8000/(.*) https://127.0.0.1/$1;
        }

        # SPA rotaları için Nginx
        location ~ ^/(dashboard|login|games|settings|twopong3d|tournamentpong)$ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            sub_filter 'http://127.0.0.1:8000' 'https://127.0.0.1';
            sub_filter_once off;
        }
    }
}