# Generated by Django 5.1.2 on 2024-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_yourmodel_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='number',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
