# Generated by Django 5.1.2 on 2024-10-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_yourmodel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('login', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('usual_full_name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('displayname', models.CharField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(blank=True, max_length=50, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('large_image', models.URLField(blank=True, null=True)),
                ('medium_image', models.URLField(blank=True, null=True)),
                ('small_image', models.URLField(blank=True, null=True)),
                ('micro_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
