# Generated by Django 5.1.2 on 2024-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_userprofile_user_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
