# Generated by Django 5.1.2 on 2024-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_userprofile_avatar_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language_settings',
            field=models.CharField(blank=True, default='tr', max_length=10, null=True),
        ),
    ]
