# Generated by Django 5.1.2 on 2024-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_userprofile_language_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_path',
            field=models.ImageField(blank=True, default='user_images/kiz.png', null=True, upload_to='user_images/'),
        ),
    ]
