# Generated by Django 5.1.2 on 2024-11-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_userprofile_avatar_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_path',
            field=models.CharField(blank=True, default='./static/images/kiz.png', max_length=255, null=True),
        ),
    ]
