# Generated by Django 5.1.2 on 2024-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_userprofile_avatar_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_path',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
