# Generated by Django 5.1.2 on 2024-11-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_userprofile_avatar_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_path',
        ),
    ]
